### ISSUE TITLE
[Suggestion] Support for using image URLs

### ISSUE THREAD

**Issue by MulverineX** [hypherionmc/simple-rpc-public#21] opened 2021-12-23 19:09 UTC
**Is your feature request related to a problem? Please describe.**
It was recently discovered that discord's ImageKey in Activity now supports URLs, it's not documented but it is already being used by thousands of PreMiD user's. The option to specify your own URL or automatically use the world/server icon should be added.

**Describe the solution you'd like**
For single player icons use the Imgur [API](https://apidocs.imgur.com/), for multiplayer icons use `https://api.mcsrvstat.us/icon/[server address]`. 

**Additional context**
Proof of feature:

https://twitter.com/PreMiDapp/status/1474069707003252739
![image](https://user-images.githubusercontent.com/12068027/147279906-f9aa4714-e08f-466d-bdfb-4f31b47d9605.png)
![image](https://user-images.githubusercontent.com/12068027/147279961-8d796bb0-2d34-433d-a811-3c23f07dfef9.png)
![image](https://user-images.githubusercontent.com/12068027/147280111-4b63bcd5-2d5d-4e15-af1d-ba2a8bfbcfdd.png)
`mp:external/cRJruHj4qNHp3LwdwWyU-G6F-zpLV7c9Hx43YBbfr6k/%3Fsqp%3D-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg%26rs%3DAMzJL3m93pBxkZxggOYiujabXNtTjic5kw/https/i.ytimg.com/vi/wKhRnZZ0cJI/sddefault.jpg`
https://github.com/PreMiD/Presences/blob/main/websites/Y/YouTube%20Music/presence.ts#L79

**Comment by hypherionmc** [comment] 2021-12-23 19:11
Wait what? Since when is that supported? Do you have any examples how this is done because I would need to modify their official library to support it

**Comment by MulverineX** [comment] 2021-12-23 19:18
https://github.com/th-ch/youtube-music/pull/524

**Comment by hypherionmc** [comment] 2021-12-23 19:37
Hmm. Okay I tested this myself now using their library and it does not work, no matter what I pass to it. Maybe this is something that was rolled out quite recently and isn't fully available to everyone yet. I have asked in the official discord api discord as well, so lets see what black magic this is lol. If this is available to everyone and I can get it to work, I will gladly add it as people have been nagging me for it ever since this mod was released

**Comment by hypherionmc** [comment] 2021-12-23 19:38
Or maybe it's one of those things like with spotify, where only they have access to that cool progress bar

**Comment by MulverineX** [comment] 2021-12-23 19:41
@hypherionmc no, PreMiD does not have exclusive API access, all discord applications they use are user-generated and they use the stock discord-rpc library. My guess is you're running into a bad regex check in the java library.

**Comment by hypherionmc** [comment] 2021-12-23 19:43
I use the official discord-rpc sdk, with a Java wrapper made by MinnDevelopment (with modifications to support buttons). I'll keep testing this. This would be a really cool feature to support

**Comment by MulverineX** [comment] 2021-12-23 19:47
Huh, there does not appear to be a regex check, interesting. You're passing largeImageKey as an image url with `.png/.jpg/.webp` 
 at the end right?

**Comment by hypherionmc** [comment] 2021-12-23 19:49
Nevermind, I am an idiot. I copied the url incorrectly. I can confirm this works with my library, so I need to remove the internal limit on the image key length and it will work

**Comment by hypherionmc** [comment] 2021-12-23 19:49
![image](https://user-images.githubusercontent.com/63595580/147285896-7ee673be-8d8e-4b13-97d8-5ead942d6297.png)

**Comment by hypherionmc** [comment] 2021-12-23 19:56
Okay, just confirmed, image urls are already working with the mod's current version, so I just need to add support for server icons. Thanks for telling me about this. I am actually taking a coding break until next year, but I just had to try this for myself.

I'll release a version with this feature either tomorrow or sunday

**Comment by MulverineX** [comment] 2021-12-23 20:00
Singleplayer worlds also have icons, and being able to set a URL yourself without the need for making your own discord application would be nice as well

**Comment by hypherionmc** [comment] 2021-12-23 20:03
Yeah. I am not very happy about having to upload data from the users pc to something like IMGUR, because people already shat their pants about the %serverip% variable, because of privacy concerns.

As for using the url, you can now actually just use a url with the default config, so you no longer need to make your own application

**Comment by MulverineX** [comment] 2021-12-23 20:04
Just add a fat disclaimer about it using the imgur API. MultiMC uses it for screenshots on request.

**Comment by hypherionmc** [comment] 2021-12-23 20:05
Sounds good. I could add a config option to opt-out of that, so that users that don't feel comfortable with this, can disable the feature all together

**Comment by hypherionmc** [comment] 2021-12-23 20:16
Okay so what I'm going to do is, I'll add the IMGUR upload feature, with a config option to disable it entirely, as well as show a prompt to people using the mod with this feature for the first time, so they can choose to use it or not. 

The amount of backlash and personal attacks I had just for including a variable that exposes the server IP you're playing on when used, kinda scares me from doing this type of stuff.

I'll let you know when I added this

**Comment by MulverineX** [comment] 2021-12-23 20:18
The server IP variable wasn't even on by default right?

**Comment by hypherionmc** [comment] 2021-12-23 20:20
In the beginning it was, and pack devs has the option to include it by default, which was a major issue for a lot of people, because they didn't take the time to remove the variable before joining a private server, so needless to say, my CF inbox was flooded with hate messages and you can even still find a "bug" report in the closed issues about this.

That's why the variable was changed to %serverip% from %ip%, so that people would need to change the variable themselves if they wanted to use it

**Comment by MulverineX** [comment] 2021-12-23 20:22
Yeah, big yikes that it was included by default. RIP that you didn't realize and got attacked for it

**Comment by hypherionmc** [comment] 2021-12-23 20:37
![image](https://user-images.githubusercontent.com/63595580/147289541-f952caf0-c208-4e6e-b735-a4fda300b3f4.png)
Jikes.... The mod will definitely hit those limits within 2-4 days

**Comment by MulverineX** [comment] 2021-12-23 21:38
Oh that's definitely not the right API, there's an anonymous one with IP based caps, I'd check out what MultiMC does.

**Comment by CDAGaming** [comment] 2022-09-20 20:58
Ay yo, when the f$$$ was this added :O

**Comment by hypherionmc** [comment] 2022-09-20 21:07
Discord silently added it sometime last year.... Looks like people either discovered it by accident, or they announced it somewhere we all missed it

**Comment by CDAGaming** [comment] 2022-09-20 22:24
![image](https://user-images.githubusercontent.com/16328918/191375575-86076b08-d494-4c26-ab29-c0dcc4589eea.png)
Ah nice, I almost have it working in my mod, though your more then welcome to take a look (Though it may not be all that useful since we use such different Systems)

**Comment by hypherionmc** [comment] 2022-09-20 22:49
That's awesome.

I've been thinking about making my own image hosting service specifically for rpc mods to bypass the limits of imgur etc.

If I do, you're more than welcome to use it as well

**Comment by CDAGaming** [comment] 2022-09-20 23:12
Nice, I'll definitly keep an eye out for that
Code should be up in my repo within another hour, nearly done polishing this up.

**Comment by MulverineX** [comment] 2022-09-21 00:17
Again, there really isn't significant limits to Imgur, there is an anonymous API you can use similar to what youtube-dl uses.

**Comment by hypherionmc** [comment] 2022-09-21 07:26
> Nice, I'll definitly keep an eye out for that Code should be up in my repo within another hour, nearly done polishing this up.

I'll give you a mention here when it's done :)

**Comment by hypherionmc** [comment] 2022-09-21 07:28
> Again, there really isn't significant limits to Imgur, there is an anonymous API you can use similar to what youtube-dl uses. Here's [multimc's usage](https://github.com/MultiMC/Launcher/blob/develop/launcher/screenshots/ImgurUpload.cpp).

Yes I know, but I've also noticed that users don't quite understand how to use it correctly, that's why I wanted to create something that supplies the data in exactly the format (And sizes) the mods expect them

**Comment by CDAGaming** [comment] 2022-09-23 02:51
https://user-images.githubusercontent.com/16328918/191883758-a4d6be6b-c7f1-4efd-8fb4-92e38ba0fa83.mp4

Also as a follow-up, Gif's also appear to work in Rich Presence (Base64 does not though)

**Comment by MulverineX** [comment] 2022-09-23 07:50
It was known that it only takes URLs, wasn't aware you could use GIFs though, that's pretty nifty.

**Comment by hypherionmc** [comment] 2022-09-23 09:13
Yeah GIF support was added a couple of months ago. It's quite nice actually

**Comment by hypherionmc** [comment] 2024-06-24 19:08
I am going to close this issue for now, as the original suggestion has been implemented, and I only kept it open to remember about our own image system, which is now tracked internally.

Thank you once again for this suggestion :)

**Closed by hypherionmc** 2024-06-24 19:08 UTC
Labels: enhancement, fixed-in-dev
