### ISSUE TITLE
Server console spam [BUG]

### ISSUE THREAD

**Issue by RockZe** [hypherionmc/simple-rpc-public#87] opened 2024-06-26 18:42 UTC
After updating the mod and a new setting in the server console, it started to give this error every 10 minutes, maybe someone has encountered this problem.

![image](https://github.com/hypherionmc/simple-rpc-public/assets/123874691/0052056e-9f5d-4fac-9228-8332fcdaafd0)

 - Mod Version: SimpleRPC-Universal-3.3.0.jar
 - Minecraft Version: 1.20.1
 - Forge/Fabric Version: 0.15.10

**Comment by hypherionmc** [comment] 2024-06-26 18:43
This isn't this mod.. This is [SDLink](https://github.com/hypherionmc/sdlink)

**Comment by RockZe** [comment] 2024-06-27 09:35
Oh, my mistake, should I recreate the request in the right section?

**Comment by hypherionmc** [comment] 2024-06-27 09:38
You can, just for record keeping. I did however look into the error, since I happened to be working on that mod last night, and found an issue.

It's caused by the tellraw relay of the mod. A work around for now is to disable tellrawRelay in the config, until we release the fix (just waiting for testing feedback before we do)

**Comment by hypherionmc** [comment] 2024-06-30 12:40
The issue in the mod this is actually from has been fixed with release 3.1.2 of SDlink

**Closed by hypherionmc** 2024-06-30 12:40 UTC
Labels: invalid
