### ISSUE TITLE
Config file resets after game is relaunched

### ISSUE THREAD

**Issue by KxttyKxt** [hypherionmc/simple-rpc-public#39] opened 2022-07-14 16:15 UTC
**Describe the bug**
When I edit the config file, it works just fine. If I save and quit the game, then relaunch the modpack in which I edited the config, the config has magically reset itself to the default config. The backup file is also the default config.

**To Reproduce**
1. Create a modpack/modded installation with this mod in it.
2. Edit anything about the mod's config, be it in-game or in the file itself.
3. Save and quit the config.
4. Verify your changes have been reflected in Discord.
5. Quit the game.
6. Reopen the modded installation.
7. See error. The DRPC will be reset.
8. See error. The config file will be reset.

**Expected behavior**
I expected my config file to remain the same after relaunching the game.

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10 Pro 21H2 19044.1766
 - JAVA Version: OpenJDK Platform Binary 16.0.1.0 (CurseForge Automatic Bundled Runtime for Minecraft 1.18.2)
 - Mod Version: 3.0.1
 - Discord Version: Stable 136607 (7f224ff)
 - Minecraft Version: 1.18.2
 - Fabric Version: 0.14.8

**Comment by hypherionmc** [comment] 2022-07-14 18:27
So basically it's replacing all your edits with the default file? That's odd.

The config file should never be touched by the mod (replaced/updated), unless the config version (which is clearly marked as do not touch in the file), is changed. 

Even then, it should still keep your edits, while simply adding the new changes, or renaming sections.

There seems to be an unconfirmed issue with configs in the latest 3.x version, but everyone that reports it, just vanishes without giving more details.

To help me with testing, can you send me a copy of the modpack where this occurs?

**Comment by hypherionmc** [comment] 2022-07-15 08:08
Thank you very much. Will check it out and give you feedback :)

**Comment by hypherionmc** [comment] 2022-07-16 16:05
@KxttyKxt Are you on discord? We did confirm some weird behavior with the mod inside that specific pack, which wasn't present when the mod was used on its own. I'm only asking cause it's difficult via github lol

**Comment by KxttyKxt** [comment] 2022-07-16 16:06
I am on Discord: `KxttyKxt#2718`

**Comment by hypherionmc** [comment] 2022-07-16 16:07
Thanks :) Will dm you now

**Closed** 2022-07-16 17:32 UTC
Labels: bug
