### ISSUE TITLE
[BUG] CRASH WHEN USING BUTTONS ON DIMENSIONS

### ISSUE THREAD

**Issue by Camawama** [hypherionmc/simple-rpc-public#45] opened 2022-08-08 02:09 UTC
**Describe the bug**
When I set buttons up for dimensions, the world Crashes Upon Loading

**To Reproduce**
1. Set a custom button for when in a Dimension
2. Open the game
3. Join a world
4. Crash

**Expected behavior**
The custom buttons should not crash the game

**Screenshots**
(no screenshot)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10 Pro 64x
 - JAVA Version: 17.0.1
 - Mod Version: simple-rpc-1.18.2-3.1.1.jar
 - Discord Version: Stable 140355 (cd30e81)
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: 40.1.69

**CONFIG FILE**
https://drive.google.com/file/d/1oHIrB80mZrhIlxaQvNkCy-Kk8tDzQpQj/view?usp=sharing

**Comment by hypherionmc** [comment] 2022-08-08 07:34
Yeah, that's a bug caused by the editor. I still need to fix that.

Replace `dimension_overrides.buttons` with `dimension_overrides.dimension.buttons` and it should work

**Comment by hypherionmc** [comment] 2022-08-08 20:41
Issue should be fixed with Editor 3.0.3

**Closed** 2022-09-20 21:08 UTC
Labels: bug, bug-in-other-software
