### ISSUE TITLE
[BUG]Error While Loading Seaopolis

### ISSUE THREAD

**Issue by Mananangal** [hypherionmc/simple-rpc-public#23] opened 2022-02-02 10:04 UTC
**Describe the bug**
When loading game, an error screen pops up. It says "Error loading mods 1 error has occurred during loading" and "Sİmple RPC encountered an error during the common_setup event phase." when looked into the crash file it says;
"Mod File: simple-rpc-1.16.5-2.7.jar
	Failure message: Simple RPC (simple-rpc) encountered an error during the common_setup event phase
		java.lang.IllegalArgumentException: Can not set boolean field me.hypherionmc.simplerpclib.configuration.ServerEntriesConfig.enabled to null value
	Mod Version: 2.7"

**To Reproduce**
1. Go to 'Open Seaopolis'
2. Click on 'Crash File'
3. Scroll down to 'Line 50'

**Expected behavior**
The modpack starting regularly

**Screenshots**
![Screenshot from 2022-02-02 12-57-31](https://user-images.githubusercontent.com/98879727/152132130-7820e85d-50bb-4ea3-888f-2c37b233aaa4.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS:Ubuntu 21.04
 - JAVA Version: Java-8 OpenJDK
 - Mod Version: Simple RPC 2.7
 - Modpack Version: Seaopolis 14.3
 - Discord Version:
 - Minecraft Version:
 - Forge/Fabric Version:

**Additional context**
Here is the crash report
[crash-2022-02-02_12.44.21-fml.txt](https://github.com/hypherionmc/simple-rpc-public/files/7985380/crash-2022-02-02_12.44.21-fml.txt)

**Comment by hypherionmc** [comment] 2022-02-02 10:09
Urgh another one caused by the server entries file. If restarting the game doesn't work, try deleting the file called `server-entries.toml` located in the simple-rpc folder and running the game again.

I will look into this on my side as well

**Comment by Mananangal** [comment] 2022-02-02 10:15
Unfortunately it didn't fix the issue.

**Comment by hypherionmc** [comment] 2022-02-02 10:54
Damn okay. I'll look at it when I get home. For now you can just remove the mod. Even if you play on a server, you should be able to connect without the mod on the client

**Comment by hypherionmc** [comment] 2022-02-07 20:07
Just an update, a fix will be released by tomorrow

**Comment by hypherionmc** [comment] 2022-02-20 11:51
Version 2.7.2 fixes this problem :)

**Closed by hypherionmc** 2022-02-20 11:51 UTC
Labels: bug, fixed
